import { GoogleGenAI } from "@google/genai";
import { Event } from "../models/Event";
import fs from "fs";
import path from "path";

type EventSummary = {
  title: string;
  category: string;
  city: string | null;
  address: string | null;
  startDate: Date;
  slug: string;
  shortDescription?: string | null;
  description: string;
  isFree: boolean;
  price: number;
  currency: string;
};

const testDataPattern = /(smoke|quality)\s/i;

function isTestEvent(event: Pick<EventSummary, "title" | "slug">): boolean {
  return event.slug.startsWith("smoke-") ||
    event.slug.startsWith("quality-") ||
    event.slug.startsWith("seed-smoke-") ||
    testDataPattern.test(event.title);
}

function eventDate(date: Date): string {
  return new Date(date).toLocaleString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function eventLocation(event: EventSummary): string {
  return event.city || event.address || "Online/TBA";
}

function eventDescription(event: EventSummary): string {
  const text = event.shortDescription || event.description;
  return text.length > 140 ? `${text.slice(0, 137)}...` : text;
}

async function getUpcomingEvents(): Promise<EventSummary[]> {
  const events = await Event.find({
    status: { $in: ["upcoming", "live"] },
    startDate: { $gte: new Date() },
  })
    .sort({ startDate: 1 })
    .limit(60)
    .lean<EventSummary[]>();

  return events.filter((event) => !isTestEvent(event)).slice(0, 30);
}

function buildEventContext(events: EventSummary[]): string {
  if (events.length === 0) {
    return "There are currently no upcoming or live non-test events in the database.";
  }

  return events.map((event) => {
    const price = event.isFree ? "Free" : `${event.currency} ${event.price}`;
    return [
      `Title: ${event.title}`,
      `Category: ${event.category}`,
      `Date: ${eventDate(event.startDate)}`,
      `Location: ${eventLocation(event)}`,
      `Price: ${price}`,
      `Slug: ${event.slug}`,
      `Description: ${eventDescription(event)}`,
    ].join("\n");
  }).join("\n\n");
}

export async function generateGlobalChatReply(userMessage: string): Promise<string> {
  const message = userMessage.trim();

  if (!process.env.GEMINI_API_KEY) {
    return "I'm sorry, I am currently unable to assist you with event recommendations because the Google Gemini API integration is not configured on the server.";
  }

  const upcomingEvents = await getUpcomingEvents();

  const systemInstruction = `
You are EventSphere Assistant, a concise event discovery assistant.

Use only the event data in DATABASE CONTEXT. Ignore any event that appears to be test or smoke data.
When the user asks for events, recommend matching events directly with name, date, location, short description, and price.
Format event recommendations as a numbered Markdown list.
If no events match, say that clearly and suggest nearby categories the user can ask for.
Never tell the user to manually check the Discover page.
End event recommendation replies by asking whether the user wants more details or help registering.

DATABASE CONTEXT:
${buildEventContext(upcomingEvents)}
`.trim();

  try {
    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: message,
      config: {
        systemInstruction,
        temperature: 0.5,
      },
    });

    return response.text || "I'm sorry, I could not generate a response. Please try again.";
  } catch (error) {
    const err = error as { message?: string };
    console.error("[AI Service] Gemini failed:", err.message);
    return "I'm sorry, I encountered an error communicating with the AI service. Please try again later.";
  }
}

export async function generateEventBanner(promptText: string): Promise<string> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured.");
  }

  try {
    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    const response = await ai.models.generateImages({
      model: "imagen-3.0-generate-002",
      prompt: `${promptText}, landscape aspect ratio 16:9, digital art style, high quality event banner`,
      config: {
        numberOfImages: 1,
        outputMimeType: "image/jpeg",
        aspectRatio: "16:9",
      },
    });

    const generatedImage = response.generatedImages?.[0];
    if (!generatedImage || !generatedImage.image?.imageBytes) {
      throw new Error("No image generated by Gemini.");
    }

    const base64Image = generatedImage.image.imageBytes;
    const buffer = Buffer.from(base64Image, "base64");
    
    const filename = `${Date.now()}-${Math.random().toString(36).slice(2)}.jpg`;
    const dir = path.join(process.cwd(), "uploads", "event-images");
    
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, filename), buffer);

    return `/uploads/event-images/${filename}`;
  } catch (error) {
    const err = error as { message?: string };
    console.warn("[AI Service] Imagen generation failed, using local fallback asset:", err.message);

    const filename = `${Date.now()}-${Math.random().toString(36).slice(2)}.png`;
    const dir = path.join(process.cwd(), "uploads", "event-images");
    
    fs.mkdirSync(dir, { recursive: true });

    let assetPath = path.join(process.cwd(), "dist", "assets", "default-banner.png");
    if (!fs.existsSync(assetPath)) {
      assetPath = path.join(process.cwd(), "src", "assets", "default-banner.png");
    }

    if (fs.existsSync(assetPath)) {
      fs.copyFileSync(assetPath, path.join(dir, filename));
    } else {
      // Ultimate absolute fallback: write a 1x1 black png
      const fallbackPng = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=", "base64");
      fs.writeFileSync(path.join(dir, filename), fallbackPng);
    }

    return `/uploads/event-images/${filename}`;
  }
}
