import type { Event } from '@/types'

const now = new Date()
const daysFromNow = (days: number, hour: number) => {
  const date = new Date(now)
  date.setDate(now.getDate() + days)
  date.setHours(hour, 0, 0, 0)
  return date.toISOString()
}

export const sampleEvents: Event[] = [
  {
    id: 'sample-mumbai-tech-meetup',
    organizer_id: 'sample-organizer-tech',
    venue_id: null,
    title: 'Mumbai Founders & Builders Meetup',
    slug: 'mumbai-founders-builders-meetup',
    description: 'A relaxed evening for startup founders, engineers, designers, and operators to swap notes, meet collaborators, and hear short talks from local builders.',
    short_description: 'Meet founders, builders, and startup operators in Mumbai.',
    banner_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    category: 'tech',
    tags: ['startups', 'networking', 'technology'],
    status: 'upcoming',
    start_date: daysFromNow(5, 18),
    end_date: daysFromNow(5, 21),
    timezone: 'Asia/Kolkata',
    is_online: false,
    online_url: null,
    address: 'Bandra Kurla Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.0688,
    longitude: 72.8703,
    capacity: 120,
    current_attendees: 68,
    price: 0,
    currency: 'INR',
    is_free: true,
    registration_deadline: null,
    min_age: null,
    max_age: null,
    requirements: null,
    is_featured: true,
    view_count: 320,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
    organizer: {
      id: 'sample-organizer-tech',
      user_id: 'sample-user-tech',
      organization_name: 'Mumbai Builder Circle',
      description: null,
      logo_url: null,
      website: null,
      social_links: null,
      verification_status: 'approved',
      verified_at: null,
      total_events: 1,
      follower_count: 240,
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  },
  {
    id: 'sample-sunday-marathon',
    organizer_id: 'sample-organizer-run',
    venue_id: null,
    title: 'Sunday Seaface 10K Run',
    slug: 'sunday-seaface-10k-run',
    description: 'Start your Sunday with a scenic 10K community run along the seaface. Pacers, hydration points, bibs, and post-run breakfast are included.',
    short_description: 'A scenic community 10K run with pacers and breakfast.',
    banner_url: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?auto=format&fit=crop&w=1200&q=80',
    category: 'marathon',
    tags: ['fitness', 'running', 'community'],
    status: 'upcoming',
    start_date: daysFromNow(9, 6),
    end_date: daysFromNow(9, 9),
    timezone: 'Asia/Kolkata',
    is_online: false,
    online_url: null,
    address: 'Marine Drive',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.9432,
    longitude: 72.8234,
    capacity: 300,
    current_attendees: 184,
    price: 499,
    currency: 'INR',
    is_free: false,
    registration_deadline: null,
    min_age: null,
    max_age: null,
    requirements: null,
    is_featured: true,
    view_count: 510,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
    organizer: {
      id: 'sample-organizer-run',
      user_id: 'sample-user-run',
      organization_name: 'Run Bombay Collective',
      description: null,
      logo_url: null,
      website: null,
      social_links: null,
      verification_status: 'approved',
      verified_at: null,
      total_events: 1,
      follower_count: 890,
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  },
  {
    id: 'sample-cafe-poetry-night',
    organizer_id: 'sample-organizer-arts',
    venue_id: null,
    title: 'Cafe Poetry & Acoustic Night',
    slug: 'cafe-poetry-acoustic-night',
    description: 'An intimate cafe evening with spoken word, acoustic sets, open mic slots, and warm conversations over coffee.',
    short_description: 'Poetry, acoustic music, open mic slots, and coffee.',
    banner_url: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80',
    category: 'cafe',
    tags: ['poetry', 'music', 'open mic'],
    status: 'upcoming',
    start_date: daysFromNow(12, 19),
    end_date: daysFromNow(12, 22),
    timezone: 'Asia/Kolkata',
    is_online: false,
    online_url: null,
    address: 'Koregaon Park',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.5362,
    longitude: 73.8938,
    capacity: 60,
    current_attendees: 37,
    price: 299,
    currency: 'INR',
    is_free: false,
    registration_deadline: null,
    min_age: null,
    max_age: null,
    requirements: null,
    is_featured: true,
    view_count: 205,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
    organizer: {
      id: 'sample-organizer-arts',
      user_id: 'sample-user-arts',
      organization_name: 'Soft Stage Sessions',
      description: null,
      logo_url: null,
      website: null,
      social_links: null,
      verification_status: 'approved',
      verified_at: null,
      total_events: 1,
      follower_count: 410,
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  },
]
